kind: pipeline
name: default


steps:
- name: test
  image: mesapy/build-mesapy:sgx
  commands:
  - ls -la /dev
  - . /opt/sgxsdk/environment
  - /start_aesm_service.sh && sleep 10 && ps aux && cd /tmp/hello_world && ./app
  volumes:
  - name: tty
    path: /dev/tty13
  - name: isgx
    path: /dev/isgx

volumes:
- name: tty
  host:
    path: /dev/tty13
- name: isgx
  host:
    path: /dev/isgx

node:
  instance: sgx
