kind: pipeline
name: default

steps:
- name: prepare
  image: plugins/git
  commands:
    - git clone -b develop https://github.com/mesalock-linux/mesalock-distro.git ../mesalock-distro
- name: backend:
  image: golang:${GO_VERSION}
  commands:
    - go build
    - go test

matrix:
  GO_VERSION:
    - latest
    - "1.7"
    - "1.6"
