pipeline:
  backend:
    image: golang
    commands:
      - go build
      - go test
  notify:
    image: drillster/drone-email
    secrets: [ notify_host, notify_username, notify_password ]
    from: ci@mesalock-linux.org
    when:
      status: [ success, changed, failure ]
