kind: pipeline
name: default

steps:
- name: backend
  image: golang:latest
  commands:
    - apt-get update
    - go build
    - go test
    - echo $USERNAME
    - echo $PASSWORD
  environment:
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password
