kind: pipeline
name: default

steps:
- name: backend
  image: golang:latest
  commands:
    - apt-get update
    - go build
    - go test
    - echo "$USERNAME"
    - echo "$PASS"
  environment:
    USERNAME:
      from_secret: username
    PASS:
      from_secret: password
