pipeline:
  backend:
    image: golang
    commands:
      - go build
      - go test
  notify:
    image: drillster/drone-email
    secrets:
      - source: notify_host
        target: plugin_host
      - source: notify_username
        target: plugin_username
      - source: notify_password
        target: plugin_password
    from: ci@mesalock-linux.org
    when:
      status: [ success, changed, failure ]
