pipeline:
  prepare:
    image: plugins/git
    commands:
      - git clone -b develop https://github.com/mesalock-linux/mesalock-distro.git ../mesalock-distro
  backend:
    image: golang
    commands:
      - go build
      - go test
  notify:
    image: drillster/drone-email
    secrets:
      - source: email_host
        target: plugin_host
      - source: email_username
        target: plugin_username
      - source: email_password
        target: plugin_password
    from: ci@mesalock-linux.org
    recipients: [ devel@mesalock-linux.org ]
    when:
      status: [ success, changed, failure ]
