kind: pipeline
name: default

commands: &commands
  - false

steps:
- name: test
  image: mesapy/build-mesapy:sgx
  commands: *commands
- name: notify
  image: drillster/drone-email
  username:
    from_secret: EMAIL_USERNAME
  password:
    from_secret: EMAIL_PASSWORD
  host:
    from_secret: EMAIL_HOST
  from:
    from_secret: EMAIL_FROM
  when:
    status:
      - failure
      - changed

node:
  instance: sgx

---

kind: pipeline
name: default2

commands: &commands
  - pwd

steps:
- name: test
  image: mesapy/build-mesapy:sgx
  commands: *commands

node:
  instance: sgx

