pipeline:
  backend:
    image: golang
    commands:
      - go build
      - go test
  notify:
    image: drillster/drone-email
    secrets:
      - host: email_host
      - username: email_username
      - password: email_password
    from: ci@mesalock-linux.org
    when:
      status: [ success, changed, failure ]
