pipeline:
  prepare:
    image: plugins/git
    commands:
      - git clone -b develop https://github.com/mesalock-linux/mesalock-distro.git ../mesalock-distro
  backend:
    image: golang
    commands:
      - go build
      - go test
  notify:
    image: drillster/drone-email
    secrets: [plugin_host, plugin_username, plugin_password, plugin_from ]
    when:
      status: [ success, changed, failure ]
